### ISSUE TITLE
solaris 10 facts are not found

### ISSUE THREAD

**Issue by sirinek** [camptocamp/facterdb#115]
The solaris 10 fact file is named solaris-10-i386.facts instead of solaris-10-i86pc.facts which is what facterdb is looking for. 

I have renamed the fact file and sent a PR. In the same PR I have included factsets for Solaris 10 on facter 2.5 and facter 3.11. The one i sent last year that got merged in was for 3.9.

**Comment by rodjek** [comment]
Fixed by #116
