### ISSUE TITLE
Update removed selinux facts

### ISSUE THREAD

**Issue by raphink** [camptocamp/facterdb#124]
Update 1a9c20c3b05a37e9c52c73151384b7977e8e8b0c to CentOS facts removed `selinux_*` facts which were listed before. @rodjek do you think you could redo these updates without deactivating selinux?

**Comment by rodjek** [comment]
This is an unfortunate artifact of generating the fact sets on different base images. I'm pulling down the official CentOS 6 vagrant image to see what the default behaviour is (selinux enabled or disabled) and will regenerate the fact sets if it defaults to selinux enabled.

**Comment by rodjek** [comment]
It does indeed ship with selinux enforcing by default. I'll rebuild the fact sets today, sorry about that!

**Comment by raphink** [comment]
Thanks very much @rodjek 	!
