### ISSUE TITLE
IP address facts have disappeared

### ISSUE THREAD

**Issue by bodgit** [camptocamp/facterdb#127]
It looks like #124/#125 has lost the `$::ipaddress` fact (along with maybe some other network interface-related facts). It almost looks like the facts have been regenerated on a machine with no network interfaces present.

**Comment by tobias-urdin** [comment]
Same here, we pinned facterdb to 0.8.0 for now.

**Comment by rodjek** [comment]
Interesting, it looks like it's only happening on facts generated from the EL7 image.
