### ISSUE TITLE
centos-7-x86 facts in 0.2.2 changed to AIO

### ISSUE THREAD

**Issue by domcleal** [camptocamp/facterdb#14]
There seems to be a difference in the `facts/2.4/centos-7-x86_64.facts` file between facterdb 0.2.1 and the latest 0.2.2 and 0.3.0 releases.  The facts appear to have been regenerated using an AIO installation, which is causing us some failures in theforeman/foreman_proxy.

The GitHub repo though doesn't show these changes, so I wonder if there are local modifications that made it into the published gem?  I'm unsure if it's an intentional change (I hope not).

https://gist.github.com/f9a45c848f87c8f4bb8e is a diff of the centos-7-x86.facts file between 0.2.1 and 0.3.0.  Note that rubysitedir changes to /opt/puppetlabs while in https://github.com/camptocamp/facterdb/blob/0.3.0/facts/2.4/centos-7-x86_64.facts#L79 it's still /usr/local.

**Comment by mcanevet** [comment]
Hmmm, I changed to script that generates the facts to use the ruby provided by puppet AIO package instead off all the mess here: https://github.com/camptocamp/facterdb/commit/e9e7dc75112a3e91f206587e93fed2af0a5f4475

So the problem is that `rubysitedir` is not the one you expect?

**Comment by domcleal** [comment]
> So the problem is that rubysitedir is not the one you expect?

Yes, I suppose it simply came as a surprise to see it change for that OS on pre-existing tests.  Now I think about it more, that's inevitable as AIO becomes the standard and you update the facts for the OS.  As you add a new set of facts for a new facterversion, what's returned by r-p-f will change.

I wonder if it's feasible to not ever refresh facts (esp between non-AIO and AIO) for a given facterversion once it's been released in facterdb?

We probably ought to simply stub/merge the facts we expect in the specs better either way.

**Comment by mcanevet** [comment]
Isn't it possible to populate it at runtime in rspec-puppet-facts like I do for `augeasversion`, `rubyversion` and `puppetversion` https://github.com/mcanevet/rspec-puppet-facts/blob/master/lib/rspec-puppet-facts.rb#L45-L49?

**Comment by mcanevet** [comment]
@domcleal what do you think of that https://github.com/mcanevet/rspec-puppet-facts/pull/19 ?

**Comment by domcleal** [comment]
I don't think overwriting it from r-p-f is going to help much, since it's probably just going to change it to an RVM path or something about where the tests are run rather than the Puppet/Facter packages that were used.

Let me close this issue because I think we need to do it via merging/stubbing of the facts in our test.  I'm not sure that we can assume which type of packages these facts use.

**Comment by ekohl** [comment]
@mcanevet maybe a more generic override framework would also solve https://github.com/mcanevet/rspec-puppet-facts/issues/14

**Comment by mcanevet** [comment]
@ekohl I'm not sur how to implement this, but PR welcome :-)
@domcleal I release `rspec-puppet-facts` 1.3.0 that dynamically set rubysitedir, does it solve your problem?

**Comment by domcleal** [comment]
@mcanevet yes it does, thank you.  I'm still not sure that we should be relying on it, as I suspect it's now setting the rubysitedir to /home/dcleal/.rvm rather than either /usr/lib or /opt/puppetlabs, but it is fixing the tests.

**Comment by ekohl** [comment]
@mcanevet what would be the correct place to discuss the issue? I'm quite sure it's not here :)

**Comment by mcanevet** [comment]
@ekohl probably here https://github.com/mcanevet/rspec-puppet-facts/issues/14
