### ISSUE TITLE
Support for more suse versions

### ISSUE THREAD

**Issue by emahags** [camptocamp/facterdb#15]
Please consider adding support for more suse versions. I'm especially interested in SLE[SD] 12 and SLED 11 but SLE[SD] 10 would be nice as well.

**Comment by mmoll** [comment]
The main thing is that somebody[tm] would need to fire up a respective boxto collect the facts, @emahags do you have access to SLES boxes?

**Comment by emahags** [comment]
@mmoll I do have access to those types of servers. I don't have access to them in vagrant though. Is there something you can run on a normal server to fetch all the data needed?

**Comment by mmoll** [comment]
I'd say (but I stand corrected) running `facter --json` on these systems and dropping the generated  output into the correct directories with the correct name should suffice.

**Comment by ekohl** [comment]
So SLES 11 and 12 have both been added. Not sure if SLES 10 is still interesting at this point given it's EOL. I'd suggest to close this issue now.

**Comment by emahags** [comment]
Great, thanks!
