### ISSUE TITLE
facterdb conflict

### ISSUE THREAD

**Issue by logicminds** [camptocamp/facterdb#157]
This was previously fixed 21 days ago via #156 .  Can we get a new release of facterdb

`Unable to activate facterdb-1.4.0, because facter-4.0.14 conflicts with facter (< 4.0.0) (Gem::ConflictError)`

**Comment by op-ct** [comment]
@raphink @rodjek Seconding this: could we get a new release of the facterdb gem?

Until a fixed gem with #156 is released, it's necessary to locally build and install the facterdb gem in order to run @logicminds' `debug::break()` in Bolt plans.  According to #161, the same problem breaks Puppet 7.

**Comment by DavidS** [comment]
There has been a release of 1.5.0 this morning.
