### ISSUE TITLE
FacterDB appears to not give a os.family for solaris 11 on facter 4

### ISSUE THREAD

**Issue by npwalker** [camptocamp/facterdb#158]
I don't know how to figure out the issue but I see that on this build my tests failed to find os.family on solaris 11.  

This issues is isolated to facter 4 because pinning to facter 2 resolves the issue.  

https://travis-ci.com/github/npwalker/recursive_file_permissions/jobs/389924871

I suspect everything one would need is in the travis output but let me know if not.

**Comment by npwalker** [comment]
okay I guess this is probably just https://github.com/camptocamp/facterdb/pull/156

and that means we just need a release containing that and I suspect this issue would go away

**Comment by DavidS** [comment]
There has been a release of 1.5.0 this morning with the pin relaxed. Feel free to re-open this or report a new issue if the problem still persists.
