### ISSUE TITLE
New gem release required prior to Puppet 7 to resolve dependency issues

### ISSUE THREAD

**Issue by sanfrancrisko** [camptocamp/facterdb#161]
The Puppet 7 release is using `facter 4` by default and given `facterdb#1.4.0` has a restriction in place of `facter < 4.0.0`, it will cause dependency resolution issues for anyone using Puppet 7.x

This restriction was removed in #156 but there has been no gem release since then. If a new gem could be released, it'll mitigate a lot of trouble when Puppet 7 goes live on `2020-11-17`.

**Comment by DavidS** [comment]
There has been a release of 1.5.0 this morning.
