### ISSUE TITLE
drop support for 1.8.7 and then remove json dependency

### ISSUE THREAD

**Issue by logicminds** [camptocamp/facterdb#18]
1.8.7 is no longer supported.  Additionally, ruby 1.9.3 comes with json in the core codebase so there is no need to list json as a dependency. 

This is causing things like:

```
[puppet@puppetdev module]$ prepl
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

```

**Comment by mmoll** [comment]
Ruby 1.8.7 is used on RHEL/CentOS/OEL 6 with non-AIO Puppets, so in the respective tests Ruby 1.8.7 is still used. This can be workarounded in the Gemfile, see e.g. the Gemfile currently used in theforeman-puppet, @logicminds could you prepare a PR with such a change?

**Comment by logicminds** [comment]
I understand that centos enjoys using really old rubies.  But who is developing puppet modules on centos 6 with ruby 1.8.7.  Puppet no longer supports it with puppet 3.8.  If your on windows you are using ruby 2.0.  If your on a mac you are running ruby 2.0. If your on some linux desktop than you are running bleeding edge.

**Comment by logicminds** [comment]
Also I assume you wanted to do something like:

```
if RUBY_VERSION.start_with? '1.8'
  gem 'json'
end
```

However, I am not sure how that would translate to a gemspec format.

**Comment by mmoll** [comment]
@logicminds as there are a lot of RHEL 6 and SLES 11 boxes out there using the system Ruby for Puppet I guess the actual number is depressingly high. It's not about developing under Ruby 1.8, but testing.

**Comment by mcanevet** [comment]
And RHEL5 is not EOL yet...
