### ISSUE TITLE
AIX Fact dumps?

### ISSUE THREAD

**Issue by petems** [camptocamp/facterdb#26]
AIX is only supported on Puppet Enterprise, and is borderline impossible to virtualize.

I have access to some AIX machines I could add this from, would that be something you'd accept a PR for? I've been developing some code against AIX and having some examples of facts in AIX would've been super helpful.

**Comment by mcanevet** [comment]
@petems if it's not virtualizable than ok. Please dump facts on a clean AIX installation so that we have only the facts available to everyone.
