### ISSUE TITLE
support for more windows editions

### ISSUE THREAD

**Issue by maxgaulhofer** [camptocamp/facterdb#30]
Please add support for:
- Windows Server 2008
- Windows Server 2008 R2
- Windows Server 2012
- Windows Server 2016
- Windows 10

**Comment by timhughes** [comment]
see #17

**Comment by rodjek** [comment]
I've added Facter 2.x and 3.x facts for these platforms in #46

**Comment by DavidS** [comment]
Fixed in #46.
