### ISSUE TITLE
Add Debian Stretch

### ISSUE THREAD

**Issue by petems** [camptocamp/facterdb#43]
Add Debian Stretch Support

**Comment by mcanevet** [comment]
Waiting for Puppetlabs to release puppet-agent packages for stretch...

**Comment by petems** [comment]
I thought we did? http://apt.puppet.com/dists/stretch/

**Comment by petems** [comment]
Ah, not agent yet 😢

**Comment by rodjek** [comment]
I've generated Facter 2.x fact sets for stretch in #47 (no 3.x facts yet as no puppet-agent packages are available for stretch yet)

**Comment by ekohl** [comment]
@rodjek I think you mean #46.

**Comment by rodjek** [comment]
D'oh, thanks @ekohl!

**Comment by DavidS** [comment]
#46 was merged.
