### ISSUE TITLE
Fact package_provider is missing

### ISSUE THREAD

**Issue by mxey** [camptocamp/facterdb#49]
The `package_provider` fact is missing, probably because Facter only outputs it if called with `--puppet`? I assume FacterDB is mostly in the used in the context of Puppet spec testing, so I think supporting Puppet-specific facts makes sense 

```
# facter --puppet package_provider
apt
```

**Comment by DavidS** [comment]
The `package_provider` fact is deployed by the [stdlib module](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/facter/package_provider.rb), which is out of scope for current facterdb, as it needs to also work for testing modules that do not depend on the stdlib module.
