### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by b4ldr** [camptocamp/facterdb#51]
Hello,

Do you still support FreeBSD.  I am getting the following error

```
No facts were found in the FacterDB for: [{:facterversion=>"/\\A2\\.5\\./", :operatingsystem=>"FreeBSD", :operatingsystemrelease=>"/^10/", :hardwaremodel=>"amd64"}]
No facts were found in the FacterDB for: [{:facterversion=>"/\\A2\\.5\\./", :operatingsystem=>"FreeBSD", :operatingsystemrelease=>"/^10/", :hardwaremodel=>"amd64"}]
No examples found.
```

I am running the following versions
  * facter (2.5.1)
  * facterdb (0.3.12)

Im not too familure with the code of this project however a naive search shows that freebsd facts only exist upto version 2.4.  so for now i have added `facter < 2.5` to my gemspec as per this comment https://github.com/camptocamp/facterdb/pull/44#issuecomment-316733588 

Thanks

**Comment by DavidS** [comment]
You analysis is correct. If you have access to FreeBSD systems, you can use the scripts in https://github.com/camptocamp/facterdb/tree/master/facts to gather facts and submit them here for publication.

**Comment by b4ldr** [comment]
I have updated the scripts and created a pull  (https://github.com/camptocamp/facterdb/pull/53)

which would update the freebsd facts

Thanks

**Comment by xaque208** [comment]
Thanks for the FreeBSD update @b4ldr.  Looking forward to it.

**Comment by xaque208** [comment]
@b4ldr Did you get a FreeBSD box working in https://github.com/camptocamp/facterdb/pull/59 ?  I'm trying to repllicate part of what you did there, but I can't get an image that works.

**Comment by xaque208** [comment]
```

**Comment by b4ldr** [comment]
@xaque208 the only difference between yours and mine is that i used `bento/freebsd-11.0`[1]
and a slightly modified `get_facts.sh`[2]

[1]https://github.com/b4ldr/facterdb/blob/update_vagrant/facts/Vagrantfile#L132
[2]https://github.com/b4ldr/facterdb/blob/update_vagrant/facts/get_facts.sh

**Comment by xaque208** [comment]
Oh I kept thinking that the shell provider was failing due to the `pkg install`, but I didn't think to check `get_facts.sh`.  I'll look again in the evening.

**Comment by xaque208** [comment]
@b4ldr See #60.  I'm unable to get NFS to mount.  It just hangs.

**Comment by b4ldr** [comment]
@xaque208 yes you need root to mount the freebsd shared folder, i have added a comment to your PR with the relevant info.  thanks

**Comment by xaque208** [comment]
Thanks @b4ldr.  I was able to get NFS mount and facter to run.  I'll need to look at this again to write the output, which looked like there might be errors on at least some of the versions, but I'll check again.

**Comment by xaque208** [comment]
I keep meaning to come back to this.  Getting FreeBSD facts updated in this repo is blocking several other PRs that I'm trying to make progress on, I've just not been working on Puppet lately.

**Comment by b4ldr** [comment]
@xaque208 i thought you refactored my pull and had it merged?  Let me know if there is something i can help with

**Comment by xaque208** [comment]
The code got merged, but I had some vagrant issues I never came back to so the facts themselves never got submitted @b4ldr.  Perhaps this week I can take another look at it.

**Comment by b4ldr** [comment]
i have created https://github.com/camptocamp/facterdb/pull/68 im getting an error from facter on freebsd 11 (see below) which is prvcenting the script running
```
root@:~ # facter
Bus error (core dumped)
```

**Comment by xaque208** [comment]
@b4ldr Make sure you set a UTF-8 LANG for the environment, and it should work.

**Comment by b4ldr** [comment]
yes thats seems to have got it

**Comment by rodjek** [comment]
As of #104, we should have up to date factsets for FreeBSD 11 & 12.
