### ISSUE TITLE
create new release

### ISSUE THREAD

**Issue by logicminds** [camptocamp/facterdb#65]
Can we create a new release with the changes that were recently merged.  I have some pending downstream gems that are going to require the next release.

**Comment by mcanevet** [comment]
@logicminds @DavidS @rodjek could you please update the CHANGELOG (maybe using PDK if this is relevant) according to recent changes. I didn't have time to look closely at them so I'm not really inclined to do it myself. Maybe this changes deserves an upgrade of the minor release number.
Once the CHANGELOG.md is good, I'll release a new version on rubygems.

**Comment by DavidS** [comment]
Opened #66 with the CHANGELOG and new version for the external fact db feature.

**Comment by xaque208** [comment]
May we get another release please?

**Comment by mcanevet** [comment]
@DavidS can you prepare a CHANGELOG please?
